testing pylint_check.yaml

diff --git a/.github/workflows/pylint_check.yaml b/.github/workflows/pylint_check.yaml
--- a/.github/workflows/pylint_check.yaml
+++ b/.github/workflows/pylint_check.yaml
@@ -15,25 +15,12 @@ on:
 jobs:
   update_python:
     runs-on: ubuntu-latest
-    name: Running testing
-    strategy:
-      matrix:
-        app: [pylint, pytest]
-        include:
-          - app: pylint
-            pip_installs: pylint pytest
-            test_command: cat action_test_files.txt | xargs python3 -m pylint --rcfile ./pylint.rc
-          - app: pytest
-            pip_installs: pytest pytest-cov
-            test_command: python3 -m pytest --cov=. -rpP --cov-report=xml > coverage.txt
-            artifacts: coverage.txt
+    name: Running pylint checks
     steps:
       - name: Current python version
         run: python3 --version || echo python3 not installed
       - name: Install Python 3.7
-        uses: actions/setup-python@v2
-        with:
-          python_version: '3.7'
+        run: sudo apt-get install -y --no-install-recommends python3.7 python3-pip && sudo ln -sfn /usr/bin/python3.7 /usr/bin/python3
         id: install_python_3_7
       - name: Updated python version
         run: python3 --version
@@ -50,7 +37,7 @@ jobs:
       - name: Update apt-get
         run: sudo apt-get update
       - name: Fetch/update pylint
-        run: python3 -m pip install --upgrade --no-cache-dir ${{ matrix.pip_installs }}
+        run: python3 -m pip install --upgrade --no-cache-dir pylint
         id: pylint-install
       - name: Fetch source code
         uses: actions/checkout@v2
@@ -72,32 +59,24 @@ jobs:
         id: install-python-pygdal
       - name: Install system requirements from source
         shell: bash
-        run: 'if [ -s "packages.txt" ]; then (cat packages.txt | sudo xargs apt-get install -y --no-install-recommends) || (echo "Failed to install additional packages" && exit 1); fi'
+        run: '[ -s "packages.txt" ] && (cat packages.txt | xargs apt-get install -y --no-install-recommends) || (echo "No addtional packages to install")'
         id: install-system-reqs
       - name: Install Python requirements from source
         shell: bash
-        run: 'if [ -s "requirements.txt" ]; then (python3 -m pip install --no-cache-dir -r requirements.txt) || (echo "Failed to install Python requirements" && exit 1); fi'
+        run: '[ -s "requirements.txt" ] && (python3 -m pip install --no-cache-dir -r requirements.txt) || (echo "No Python packages to install")'
         id: install-python-reqs
       - name: Run action pylint script
         shell: bash
-        run: 'if [ -s ".github/workflows/action_pylint.sh" ]; then (chmod +x ".github/workflows/action_pylint.sh" && ./.github/workflows/action_pylint.sh) || (echo "Error running shell script" && exit 1); fi'
+        run: '[ -s "action_pylint.sh" ] && (chmod +x "action_pylint.sh" && ./action_pylint.sh) || (echo "Not running special action script - empty or not found")'
         id: run-special-action-script
       - name: Fetching pylint.rc file
-        if: ${{ matrix.app == 'pylint' }}
         run: wget https://raw.githubusercontent.com/AgPipeline/Organization-info/master/pylint.rc
         id: fetch_pylint_resource
       - name: Listing
         run: ls -la
       - name: Files to be linted
-        run: cat action_test_files.txt
-      - name: Running Test
-        run: ${{ matrix.test_command }}
-      - name: Upload testing artifact
-        uses: actions/upload-artifact@v2
-        with:
-          name: testing_artifacts
-          path: ${{ matrix.artifacts }}
-        if: ${{ matrix.artifacts }}
-        - name: Upload coverage to Codecov
-          uses: codecov/codecov-action@v1
-          if: ${{ matrix.app == 'pytest' }}
+        run: cat action_pylint_files.txt
+      - name: Running pylint
+        run: cat action_pylint_files.txt | xargs python3 -m pylint --rcfile ./pylint.rc
+      - name: Running pytest
+        run: pytest
