testing pygdal install

diff --git a/.github/workflows/testing_checks.yaml b/.github/workflows/testing_checks.yaml
--- a/.github/workflows/testing_checks.yaml
+++ b/.github/workflows/testing_checks.yaml
@@ -4,6 +4,7 @@ on:
     branches:
       - master
       - develop
+      - adding_tests
   pull_request:
     branches:
       - master
@@ -12,70 +13,83 @@ on:
       - v*
 
 jobs:
-  update_python:
+  testing:
     runs-on: ubuntu-latest
-    name: Running pylint checks
+    name: Running testing
+    strategy:
+      matrix:
+          app: [pylint, pytest]
+          include:
+            - app: pylint
+              pip_installs: pylint pytest
+              test_command: cat action_test_files.txt | xargs python3 -m pylint --rcfile ./pylint.rc
+            - app: pytest
+              pip_installs: pytest pytest-cov
+              test_command: python3 -m pytest --cov=. -rpP --cov-report=xml > coverage.txt
+              artifacts: coverage.txt
     steps:
       - name: Current python version
         run: python3 --version || echo python3 not installed
       - name: Install Python 3.7
-        run: sudo apt-get install -y --no-install-recommends python3.7 python3-pip && sudo ln -sfn /usr/bin/python3.7 /usr/bin/python3
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.7'
         id: install_python_3_7
       - name: Updated python version
         run: python3 --version
+      - name: PYTHONPATH environment variable
+        run: echo "PYTHONPATH is ${PYTHONPATH}"
       - name: Update pip
         run: python3 -m pip install --upgrade --no-cache-dir pip
-        id: pip-install
       - name: Fetch/update setuptools
         run: python3 -m pip install --upgrade --no-cache-dir setuptools
-        id: setuptools-install
       - name: Install python-apt
         run: sudo apt-get install -y python-apt
       - name: HACK to fix apt-get update problem w/ different python versions
         run: 'cd /usr/lib/python3/dist-packages && sudo cp apt_pkg.cpython-36m-x86_64-linux-gnu.so apt_pkg.so'
       - name: Update apt-get
         run: sudo apt-get update
-      - name: Fetch/update pylint
-        run: python3 -m pip install --upgrade --no-cache-dir pylint
-        id: pylint-install
+      - name: Fetch/update testing pip installations
+        run: python3 -m pip install --upgrade --no-cache-dir ${{ matrix.pip_installs }}
       - name: Fetch source code
         uses: actions/checkout@v2
-        id: fetch-source
       - name: Finding files
-        run: find . -type f -name "*.py" > action_pylint_files.txt
-        id: find-python-files
+        run: find . -type f -name "*.py" > action_test_files.txt
       - name: Install system requirements
         shell: bash
         run: 'sudo apt-get install -y python3-gdal gdal-bin libgdal-dev gcc g++ python3.7-dev'
-        id: install-gdal-other-reqs
       - name: Install Python numpy
         shell: bash
-        run: 'python3 -m pip install --upgrade --no-cache-dir numpy wheel terrautils'
-        id: install-python-numpy
+        run: 'python3 -m pip install --upgrade --no-cache-dir numpy wheel'
       - name: Install Python pygdal
         shell: bash
-        run: 'sudo python3 -m pip install --no-cache-dir pygdal==2.2.3.5'
-        id: install-python-pygdal
+        run: 'python3 -m pip install --no-cache-dir pygdal'
       - name: Install system requirements from source
         shell: bash
-        run: '[ -s "packages.txt" ] && (cat packages.txt | xargs apt-get install -y --no-install-recommends) || (echo "No addtional packages to install")'
-        id: install-system-reqs
+        run: 'if [ -s "packages.txt" ]; then (cat packages.txt | sudo xargs apt-get install -y --no-install-recommends) || (echo "Failed to install additional packages" && exit 1); fi'
       - name: Install Python requirements from source
         shell: bash
-        run: '[ -s "requirements.txt" ] && (python3 -m pip install --no-cache-dir -r requirements.txt) || (echo "No Python packages to install")'
-        id: install-python-reqs
+        run: 'if [ -s "requirements.txt" ]; then (python3 -m pip install --no-cache-dir -r requirements.txt) || (echo "Failed to install Python requirements" && exit 1); fi'
       - name: Run action pylint script
         shell: bash
-        run: '[ -s "action_pylint.sh" ] && (chmod +x "action_pylint.sh" && ./action_pylint.sh) || (echo "Not running special action script - empty or not found")'
-        id: run-special-action-script
+        run: 'if [ -s ".github/workflows/action_pylint.sh" ]; then (chmod +x ".github/workflows/action_pylint.sh" && ./.github/workflows/action_pylint.sh) || (echo "Error running shell script" && exit 1); fi'
       - name: Fetching pylint.rc file
+        if: ${{ matrix.app == 'pylint' }}
         run: wget https://raw.githubusercontent.com/AgPipeline/Organization-info/master/pylint.rc
-        id: fetch_pylint_resource
+      - name: Set execution permission for testing
+        run: chmod +x tests/test_agpypeline.py
       - name: Listing
         run: ls -la
-      - name: Files to be linted
-        run: cat action_pylint_files.txt
-      - name: Running pylint
-        run: cat action_pylint_files.txt | xargs python3 -m pylint --rcfile ./pylint.rc
-      - name: Running pytest
-        run: pytest
+      - name: Files to be tested
+        run: cat action_test_files.txt
+      - name: Running test
+        run: ${{ matrix.test_command }}
+      - name: Upload testing artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: testing_artifacts
+          path: ${{ matrix.artifacts }}
+        if: ${{ matrix.artifacts }}
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v1
+        if: ${{ matrix.app == 'pytest' }}
