made changes baded on pull-request

diff --git a/.github/workflows/testing_checks.yaml b/.github/workflows/testing_checks.yaml
--- a/.github/workflows/testing_checks.yaml
+++ b/.github/workflows/testing_checks.yaml
@@ -57,7 +57,7 @@ jobs:
         id: install-python-pygdal
       - name: Install system requirements from source
         shell: bash
-        run: '[ -s "packages.txt" ] && (cat packages.txt | sudo xargs apt-get install -y --no-install-recommends) || (echo "No addtional packages to install")'
+        run: '[ -s "packages.txt" ] && (cat packages.txt | sudo xargs apt-get install -y --no-install-recommends) || (echo "Failed to install packages")'
         id: install-system-reqs
       - name: Install Python requirements from source
         shell: bash
